### ISSUE TITLE
Using decimal in std::complex

### ISSUE THREAD

**Issue by ser90368141** [cppalliance/decimal#426]
Hi guys! I am trying to use this library in my project. I want to calculate `std::acos` for `std::complex<boost::decimal::decimal64>` type, but there is some compiler error:
```
[build] /usr/include/c++/13.2.1/complex:2020:26: error: conversion from ‘long double’ to non-scalar type ‘const boost::decimal::decimal64’ requested
[build]  2020 |       const _Tp __pi_2 = 1.5707963267948966192313216916397514L;
```
Thanks!

**Comment by mborland** [comment]
I think this is similar to any issue I ran into with integers recently: https://github.com/cppalliance/decimal/issues/409. I'll add the missing operators tomorrow, and hopefully that fixes things.

**Comment by ckormanyos** [comment]
Interesting case. At the moment, std::complex is only specified to work with one of float, double, or long double.

If Decimal ever gets into Boost, and then into C++, how wot the Standard deal with it as a template parameter to complex?

I agree with getting it to work for a bunch of local compilers. But instantiating complex with these decimal types is and will remain non standard - until standardized

**Comment by mborland** [comment]
The current draft of the C++ standard on complex numbers (section 28.4.1) reads:

The effect of instantiating the template complex for any type that is not a cv-unqualified floating-point type (6.8.2) is unspecified. Specializations of complex for cv-unqualified floating-point types are trivially copyable literal types (6.8.1).

If the result of a function is not mathematically defined or not in the range of representable values for its type, the behavior is undefined.

This used to specify `float`, `double`, and `long double`. Since decimal64 meets the requirements of trivially copyable numeric floating-point type I think it should be fine. I am not a language lawyer though.

**Comment by mborland** [comment]
Should be fixed by the linked PR. GCC 13 runs fine, but Clang 17 does not. Clang seems to make fully-qualified calls to say `std::sqrt` which inhibits the decimal overloads from being found via ADL. I could implicitly allow decimal types to be converted into floating point types, but that feels dangerous.

**Comment by ser90368141** [comment]
@mborland Thanks for the quick fix! After merge my project compiles successfully. I will let you know if I find any other issues while testing my project.
I would also like to be able to call assignment for integer data types:
```
error: conversion from ‘int’ to non-scalar type ‘boost::decimal::decimal64’ requested
[build]    34 |     boost::decimal::decimal64 a = 42;
[build]       |                                   ^~
```

**Comment by mborland** [comment]
> @mborland Thanks for the quick fix! After merge my project compiles successfully. I will let you know if I find any other issues while testing my project. I would also like to be able to call assignment for integer data types:
> 
> ```
> error: conversion from ‘int’ to non-scalar type ‘boost::decimal::decimal64’ requested
> [build]    34 |     boost::decimal::decimal64 a = 42;
> [build]       |                                   ^~
> ```

The integer constructor is marked `explicit`. You can do:


```
boost::decimal::decimal64 a {42};
auto b = static_cast<boost::decimal::decimal64>(42);
```

You can also construct non-integers from integers:

```
boost::decimal::decimal64 c {42,-1}; // 4.2
```

**Comment by mborland** [comment]
FYI I am going to revert to previous behavior of explicit conversions from binary floats:`https://github.com/cppalliance/decimal/pull/506`. I added a configuration macro `BOOST_DECIMAL_ALLOW_IMPLICIT_CONVERSIONS` that will allow this to keep working and used your example in the docs.
